import type { Customer } from "@/types/crm"

export const CRM_CUSTOMERS: Customer[] = [
  {
    id: "cust_1",
    name: "Ahmet Yılmaz",
    phone: "0532 123 45 67",
    email: "ahmet.yilmaz@email.com",
    memberSince: "2023-03-15",
    totalSpend: 4850,
    totalVisits: 32,
    lastVisit: "2026-05-09",
    walletBalance: 250,
    isVip: true,
    notes: "Hafta sonları tercih ediyor. Doğum günü paketi almak istiyor.",
    allergies: "Fındık alerjisi",
    avatarColor: "from-violet-500 to-purple-600",
    children: [
      { id: "ch1", name: "Can Yılmaz", age: 7, totalVisits: 20, favoritePackage: "60dk", lastVisit: "2026-05-09" },
      { id: "ch2", name: "Ece Yılmaz", age: 5, totalVisits: 12, favoritePackage: "30dk", lastVisit: "2026-05-09" },
    ],
    visits: [
      { id: "v1", date: "2026-05-09", childName: "Can Yılmaz", duration: "60 dk", packageType: "60dk", paymentMethod: "card", staffName: "Ayşe H.", amount: 150 },
      { id: "v2", date: "2026-05-09", childName: "Ece Yılmaz", duration: "30 dk", packageType: "30dk", paymentMethod: "card", staffName: "Ayşe H.", amount: 100 },
      { id: "v3", date: "2026-04-28", childName: "Can Yılmaz", duration: "90 dk", packageType: "90dk", paymentMethod: "wallet", staffName: "Murat K.", amount: 200 },
      { id: "v4", date: "2026-04-20", childName: "Can Yılmaz", duration: "60 dk", packageType: "60dk", paymentMethod: "cash", staffName: "Selin T.", amount: 150 },
      { id: "v5", date: "2026-04-12", childName: "Ece Yılmaz", duration: "30 dk", packageType: "30dk", paymentMethod: "card", staffName: "Ayşe H.", amount: 100 },
    ],
    walletTransactions: [
      { id: "wt1", date: "2026-04-01", type: "load", amount: 500, balance: 750, description: "Cüzdan yükleme", staffName: "Murat K." },
      { id: "wt2", date: "2026-04-28", type: "use", amount: -200, balance: 550, description: "Can Yılmaz — 90dk paket" },
      { id: "wt3", date: "2026-05-01", type: "bonus", amount: 50, balance: 600, description: "Sadakat bonusu" },
      { id: "wt4", date: "2026-05-05", type: "use", amount: -100, balance: 500, description: "Ece Yılmaz — 30dk paket" },
      { id: "wt5", date: "2026-05-08", type: "use", amount: -250, balance: 250, description: "Doğum günü etkinliği" },
    ],
    organizations: [
      { id: "org1", type: "birthday", title: "Can'ın 7. Doğum Günü", date: "2026-03-20", participants: 15, amount: 1200, status: "completed" },
      { id: "org2", type: "reservation", title: "Hafta Sonu Rezervasyonu", date: "2026-05-18", participants: 3, amount: 450, status: "upcoming" },
    ],
    staffNotes: [
      { id: "n1", date: "2026-05-09", type: "general", content: "Müşteri doğum günü için fiyat sordu, bilgi verildi.", staffName: "Ayşe H." },
      { id: "n2", date: "2026-04-20", type: "allergy", content: "Can'ın fındık alerjisi var, atıştırmalık verilmemeli.", staffName: "Selin T." },
    ],
    monthlyStats: [
      { month: "Ara", visits: 2, spend: 300 },
      { month: "Oca", visits: 3, spend: 450 },
      { month: "Şub", visits: 4, spend: 600 },
      { month: "Mar", visits: 5, spend: 1700 },
      { month: "Nis", visits: 8, spend: 1200 },
      { month: "May", visits: 4, spend: 600 },
    ],
  },
  {
    id: "cust_2",
    name: "Fatma Kaya",
    phone: "0543 987 65 43",
    email: "fatma.kaya@email.com",
    memberSince: "2024-01-10",
    totalSpend: 1850,
    totalVisits: 14,
    lastVisit: "2026-05-07",
    walletBalance: 0,
    isVip: false,
    notes: "",
    allergies: "",
    avatarColor: "from-pink-500 to-rose-600",
    children: [
      { id: "ch3", name: "Elif Kaya", age: 6, totalVisits: 14, favoritePackage: "30dk", lastVisit: "2026-05-07" },
    ],
    visits: [
      { id: "v6", date: "2026-05-07", childName: "Elif Kaya", duration: "30 dk", packageType: "30dk", paymentMethod: "cash", staffName: "Murat K.", amount: 100 },
      { id: "v7", date: "2026-04-25", childName: "Elif Kaya", duration: "60 dk", packageType: "60dk", paymentMethod: "cash", staffName: "Emre D.", amount: 150 },
      { id: "v8", date: "2026-04-10", childName: "Elif Kaya", duration: "30 dk", packageType: "30dk", paymentMethod: "card", staffName: "Ayşe H.", amount: 100 },
    ],
    walletTransactions: [],
    organizations: [],
    staffNotes: [],
    monthlyStats: [
      { month: "Ara", visits: 1, spend: 100 },
      { month: "Oca", visits: 2, spend: 250 },
      { month: "Şub", visits: 2, spend: 300 },
      { month: "Mar", visits: 3, spend: 450 },
      { month: "Nis", visits: 4, spend: 550 },
      { month: "May", visits: 2, spend: 200 },
    ],
  },
  {
    id: "cust_3",
    name: "Mehmet Demir",
    phone: "0555 321 98 76",
    email: "mehmet.demir@email.com",
    memberSince: "2023-06-22",
    totalSpend: 9200,
    totalVisits: 58,
    lastVisit: "2026-05-10",
    walletBalance: 500,
    isVip: true,
    notes: "Üç çocukla gelir. Grup indirimi için görüşülmeli.",
    allergies: "Ali'nin süt alerjisi var",
    avatarColor: "from-emerald-500 to-green-600",
    children: [
      { id: "ch4", name: "Ali Demir", age: 8, totalVisits: 25, favoritePackage: "90dk", lastVisit: "2026-05-10" },
      { id: "ch5", name: "Ayşe Demir", age: 4, totalVisits: 18, favoritePackage: "30dk", lastVisit: "2026-05-10" },
      { id: "ch6", name: "Hasan Demir", age: 11, totalVisits: 15, favoritePackage: "60dk", lastVisit: "2026-05-10" },
    ],
    visits: [
      { id: "v9", date: "2026-05-10", childName: "Ali Demir", duration: "90 dk", packageType: "90dk", paymentMethod: "wallet", staffName: "Selin T.", amount: 200 },
      { id: "v10", date: "2026-05-10", childName: "Ayşe Demir", duration: "30 dk", packageType: "30dk", paymentMethod: "wallet", staffName: "Selin T.", amount: 100 },
      { id: "v11", date: "2026-05-10", childName: "Hasan Demir", duration: "60 dk", packageType: "60dk", paymentMethod: "wallet", staffName: "Selin T.", amount: 150 },
      { id: "v12", date: "2026-04-30", childName: "Ali Demir", duration: "90 dk", packageType: "90dk", paymentMethod: "card", staffName: "Emre D.", amount: 200 },
    ],
    walletTransactions: [
      { id: "wt10", date: "2026-03-01", type: "load", amount: 1000, balance: 1000, description: "Toplu yükleme", staffName: "Ayşe H." },
      { id: "wt11", date: "2026-03-15", type: "use", amount: -450, balance: 550, description: "3 çocuk — haftalık" },
      { id: "wt12", date: "2026-04-01", type: "bonus", amount: 100, balance: 650, description: "VIP sadakat bonusu" },
      { id: "wt13", date: "2026-04-15", type: "use", amount: -450, balance: 200, description: "3 çocuk — haftalık" },
      { id: "wt14", date: "2026-05-01", type: "load", amount: 500, balance: 700, description: "Cüzdan yükleme" },
      { id: "wt15", date: "2026-05-10", type: "use", amount: -200, balance: 500, description: "Günlük kullanım" },
    ],
    organizations: [
      { id: "org3", type: "birthday", title: "Ali'nin 8. Doğum Günü", date: "2026-02-14", participants: 20, amount: 1800, status: "completed" },
      { id: "org4", type: "birthday", title: "Ayşe'nin 4. Doğum Günü", date: "2025-11-05", participants: 12, amount: 1200, status: "completed" },
      { id: "org5", type: "reservation", title: "Yaz Dönemi Aboneliği", date: "2026-06-01", participants: 3, amount: 2400, status: "upcoming" },
    ],
    staffNotes: [
      { id: "n3", date: "2026-05-10", type: "general", content: "Abonelik sistemi hakkında bilgi istedi. Fiyat teklifi hazırlanmalı.", staffName: "Selin T." },
      { id: "n4", date: "2026-04-30", type: "allergy", content: "Ali'ye kesinlikle süt ürünü verilmemeli.", staffName: "Emre D." },
      { id: "n5", date: "2026-03-20", type: "general", content: "VIP statü için uygun, sistem üzerinden işaretlendi.", staffName: "Ayşe H." },
    ],
    monthlyStats: [
      { month: "Ara", visits: 6, spend: 1350 },
      { month: "Oca", visits: 8, spend: 1800 },
      { month: "Şub", visits: 9, spend: 3800 },
      { month: "Mar", visits: 12, spend: 2700 },
      { month: "Nis", visits: 11, spend: 2475 },
      { month: "May", visits: 5, spend: 1125 },
    ],
  },
  {
    id: "cust_4",
    name: "Zeynep Arslan",
    phone: "0506 741 25 89",
    email: "",
    memberSince: "2025-09-03",
    totalSpend: 760,
    totalVisits: 7,
    lastVisit: "2026-05-10",
    walletBalance: 150,
    isVip: false,
    notes: "",
    allergies: "",
    avatarColor: "from-sky-500 to-blue-600",
    children: [
      { id: "ch7", name: "Mert Arslan", age: 9, totalVisits: 7, favoritePackage: "60dk", lastVisit: "2026-05-10" },
    ],
    visits: [
      { id: "v13", date: "2026-05-10", childName: "Mert Arslan", duration: "60 dk", packageType: "60dk", paymentMethod: "cash", staffName: "Selin T.", amount: 150 },
      { id: "v14", date: "2026-04-18", childName: "Mert Arslan", duration: "60 dk", packageType: "60dk", paymentMethod: "wallet", staffName: "Murat K.", amount: 150 },
    ],
    walletTransactions: [
      { id: "wt20", date: "2026-04-18", type: "load", amount: 300, balance: 300, description: "İlk yükleme", staffName: "Murat K." },
      { id: "wt21", date: "2026-04-18", type: "use", amount: -150, balance: 150, description: "Mert Arslan — 60dk" },
    ],
    organizations: [],
    staffNotes: [],
    monthlyStats: [
      { month: "Ara", visits: 0, spend: 0 },
      { month: "Oca", visits: 1, spend: 150 },
      { month: "Şub", visits: 2, spend: 300 },
      { month: "Mar", visits: 1, spend: 150 },
      { month: "Nis", visits: 2, spend: 300 },
      { month: "May", visits: 1, spend: 150 },
    ],
  },
  {
    id: "cust_5",
    name: "Hasan Öztürk",
    phone: "0544 852 36 14",
    email: "hasan.ozturk@email.com",
    memberSince: "2022-11-18",
    totalSpend: 15600,
    totalVisits: 94,
    lastVisit: "2026-05-08",
    walletBalance: 1200,
    isVip: true,
    notes: "En eski VIP müşterimiz. Özel indirim uygulanıyor.",
    allergies: "",
    avatarColor: "from-amber-500 to-orange-600",
    children: [
      { id: "ch8", name: "Selin Öztürk", age: 7, totalVisits: 48, favoritePackage: "90dk", lastVisit: "2026-05-08" },
      { id: "ch9", name: "Cem Öztürk", age: 9, totalVisits: 46, favoritePackage: "Serbest", lastVisit: "2026-05-08" },
    ],
    visits: [
      { id: "v15", date: "2026-05-08", childName: "Selin Öztürk", duration: "90 dk", packageType: "90dk", paymentMethod: "wallet", staffName: "Emre D.", amount: 200 },
      { id: "v16", date: "2026-05-08", childName: "Cem Öztürk", duration: "Serbest", packageType: "Serbest", paymentMethod: "wallet", staffName: "Emre D.", amount: 250 },
      { id: "v17", date: "2026-05-01", childName: "Selin Öztürk", duration: "90 dk", packageType: "90dk", paymentMethod: "wallet", staffName: "Ayşe H.", amount: 200 },
      { id: "v18", date: "2026-04-25", childName: "Cem Öztürk", duration: "Serbest", packageType: "Serbest", paymentMethod: "wallet", staffName: "Murat K.", amount: 250 },
    ],
    walletTransactions: [
      { id: "wt30", date: "2026-04-01", type: "load", amount: 2000, balance: 2000, description: "Aylık yükleme", staffName: "Ayşe H." },
      { id: "wt31", date: "2026-04-01", type: "bonus", amount: 200, balance: 2200, description: "VIP %10 bonus" },
      { id: "wt32", date: "2026-04-15", type: "use", amount: -500, balance: 1700, description: "Haftalık kullanım" },
      { id: "wt33", date: "2026-04-30", type: "use", amount: -500, balance: 1200, description: "Haftalık kullanım" },
    ],
    organizations: [
      { id: "org6", type: "birthday", title: "Selin'in 7. Doğum Günü", date: "2025-08-12", participants: 25, amount: 2200, status: "completed" },
      { id: "org7", type: "birthday", title: "Cem'in 9. Doğum Günü", date: "2024-12-05", participants: 22, amount: 2000, status: "completed" },
      { id: "org8", type: "reservation", title: "Ağustos Tatili Paketi", date: "2026-08-01", participants: 2, amount: 3000, status: "upcoming" },
    ],
    staffNotes: [
      { id: "n6", date: "2026-05-08", type: "general", content: "Ağustos için tatil paketi rezervasyonu yaptı.", staffName: "Emre D." },
      { id: "n7", date: "2026-03-01", type: "general", content: "VIP özel indirim anlaşması yenilendi.", staffName: "Ayşe H." },
    ],
    monthlyStats: [
      { month: "Ara", visits: 12, spend: 2750 },
      { month: "Oca", visits: 14, spend: 3200 },
      { month: "Şub", visits: 16, spend: 3650 },
      { month: "Mar", visits: 18, spend: 4100 },
      { month: "Nis", visits: 16, spend: 3650 },
      { month: "May", visits: 8, spend: 1825 },
    ],
  },
  {
    id: "cust_6",
    name: "Leyla Yıldız",
    phone: "0532 999 00 11",
    email: "leyla.yildiz@email.com",
    memberSince: "2026-04-20",
    totalSpend: 300,
    totalVisits: 3,
    lastVisit: "2026-05-05",
    walletBalance: 0,
    isVip: false,
    notes: "Yeni müşteri. Yakın zamanda üye oldu.",
    allergies: "",
    avatarColor: "from-teal-500 to-cyan-600",
    children: [
      { id: "ch10", name: "Buse Yıldız", age: 6, totalVisits: 3, favoritePackage: "60dk", lastVisit: "2026-05-05" },
    ],
    visits: [
      { id: "v19", date: "2026-05-05", childName: "Buse Yıldız", duration: "60 dk", packageType: "60dk", paymentMethod: "card", staffName: "Selin T.", amount: 150 },
      { id: "v20", date: "2026-04-28", childName: "Buse Yıldız", duration: "60 dk", packageType: "60dk", paymentMethod: "card", staffName: "Murat K.", amount: 150 },
    ],
    walletTransactions: [],
    organizations: [],
    staffNotes: [
      { id: "n8", date: "2026-04-20", type: "general", content: "İlk ziyaret, memnun ayrıldı. Tekrar geleceğini belirtti.", staffName: "Murat K." },
    ],
    monthlyStats: [
      { month: "Ara", visits: 0, spend: 0 },
      { month: "Oca", visits: 0, spend: 0 },
      { month: "Şub", visits: 0, spend: 0 },
      { month: "Mar", visits: 0, spend: 0 },
      { month: "Nis", visits: 2, spend: 300 },
      { month: "May", visits: 1, spend: 150 },
    ],
  },
  {
    id: "cust_7",
    name: "Osman Kara",
    phone: "0543 888 77 66",
    email: "",
    memberSince: "2023-07-14",
    totalSpend: 2400,
    totalVisits: 18,
    lastVisit: "2026-03-15",
    walletBalance: 0,
    isVip: false,
    notes: "Son 2 aydır uğramadı.",
    allergies: "",
    avatarColor: "from-red-500 to-rose-600",
    children: [
      { id: "ch11", name: "Taha Kara", age: 8, totalVisits: 18, favoritePackage: "90dk", lastVisit: "2026-03-15" },
    ],
    visits: [
      { id: "v21", date: "2026-03-15", childName: "Taha Kara", duration: "90 dk", packageType: "90dk", paymentMethod: "cash", staffName: "Emre D.", amount: 200 },
      { id: "v22", date: "2026-03-01", childName: "Taha Kara", duration: "60 dk", packageType: "60dk", paymentMethod: "cash", staffName: "Ayşe H.", amount: 150 },
    ],
    walletTransactions: [],
    organizations: [],
    staffNotes: [
      { id: "n9", date: "2026-03-15", type: "general", content: "Uzun süre uğramamış. Geri döndü, memnun görünüyor.", staffName: "Emre D." },
    ],
    monthlyStats: [
      { month: "Ara", visits: 3, spend: 500 },
      { month: "Oca", visits: 3, spend: 500 },
      { month: "Şub", visits: 2, spend: 350 },
      { month: "Mar", visits: 2, spend: 350 },
      { month: "Nis", visits: 0, spend: 0 },
      { month: "May", visits: 0, spend: 0 },
    ],
  },
  {
    id: "cust_8",
    name: "Aylin Çelik",
    phone: "0555 777 44 33",
    email: "aylin.celik@email.com",
    memberSince: "2024-08-05",
    totalSpend: 3100,
    totalVisits: 22,
    lastVisit: "2026-05-03",
    walletBalance: 350,
    isVip: false,
    notes: "Doğum günü organizasyonu yapmak istiyor.",
    allergies: "",
    avatarColor: "from-indigo-500 to-violet-600",
    children: [
      { id: "ch12", name: "Defne Çelik", age: 5, totalVisits: 15, favoritePackage: "60dk", lastVisit: "2026-05-03" },
      { id: "ch13", name: "Can Çelik", age: 8, totalVisits: 7, favoritePackage: "90dk", lastVisit: "2026-05-03" },
    ],
    visits: [
      { id: "v23", date: "2026-05-03", childName: "Defne Çelik", duration: "60 dk", packageType: "60dk", paymentMethod: "wallet", staffName: "Ayşe H.", amount: 150 },
      { id: "v24", date: "2026-05-03", childName: "Can Çelik", duration: "90 dk", packageType: "90dk", paymentMethod: "wallet", staffName: "Ayşe H.", amount: 200 },
      { id: "v25", date: "2026-04-20", childName: "Defne Çelik", duration: "60 dk", packageType: "60dk", paymentMethod: "card", staffName: "Selin T.", amount: 150 },
    ],
    walletTransactions: [
      { id: "wt40", date: "2026-04-15", type: "load", amount: 700, balance: 700, description: "Cüzdan yükleme", staffName: "Selin T." },
      { id: "wt41", date: "2026-05-03", type: "use", amount: -350, balance: 350, description: "İki çocuk günlük" },
    ],
    organizations: [
      { id: "org9", type: "birthday", title: "Defne'nin 5. Doğum Günü", date: "2026-06-15", participants: 18, amount: 1500, status: "upcoming" },
    ],
    staffNotes: [
      { id: "n10", date: "2026-05-03", type: "general", content: "Haziran'daki doğum günü için detay toplandı.", staffName: "Ayşe H." },
    ],
    monthlyStats: [
      { month: "Ara", visits: 2, spend: 350 },
      { month: "Oca", visits: 3, spend: 525 },
      { month: "Şub", visits: 4, spend: 700 },
      { month: "Mar", visits: 4, spend: 700 },
      { month: "Nis", visits: 5, spend: 875 },
      { month: "May", visits: 4, spend: 700 },
    ],
  },
]

export function getCustomerById(id: string): Customer | undefined {
  return CRM_CUSTOMERS.find((c) => c.id === id)
}

export function daysSinceLastVisit(lastVisit: string): number {
  // Calendar-day based (floors both ends to local midnight) so "Bugün" flips to
  // "Dün" at 00:00, not after a rolling 24 hours. See calendarDaysAgo.
  const then = new Date(lastVisit)
  if (isNaN(then.getTime())) return 0
  const now = new Date()
  const a = new Date(then.getFullYear(), then.getMonth(), then.getDate()).getTime()
  const b = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()
  return Math.max(0, Math.round((b - a) / 86_400_000))
}
