import type { Organization } from "@/types/organizasyon"
import { ORG_PACKAGES } from "@/types/organizasyon"

export { ORG_PACKAGES }

export const ORGANIZATIONS: Organization[] = [
  {
    id: "org_1",
    name: "Can'ın 8. Doğum Günü 🎂",
    childName: "Can Yılmaz",
    childAge: 8,
    parentName: "Ahmet Yılmaz",
    parentPhone: "0532 123 45 67",
    packageId: "pkg_premium",
    date: "2026-05-18",
    startTime: "14:00",
    endTime: "18:00",
    status: "upcoming",
    paymentStatus: "deposit",
    totalAmount: 1800,
    depositAmount: 500,
    paidAmount: 500,
    childCount: 16,
    extraChildCount: 0,
    notes: "Uzay teması istendi. Pasta özel sipariş.",
    specialRequests: "Uzay temalı dekorasyon. NASA logosu pasta üzerinde olsun.",
    decorTheme: "Uzay Teması 🚀",
    responsibleStaff: "Ayşe H.",
    children: [
      { id: "oc1", name: "Can Yılmaz", age: 8, attendance: "expected", isExtra: false, parentName: "Ahmet Yılmaz" },
      { id: "oc2", name: "Emre Çelik", age: 8, attendance: "expected", isExtra: false, parentName: "Selma Çelik" },
      { id: "oc3", name: "Kerem Arslan", age: 7, attendance: "expected", isExtra: false },
      { id: "oc4", name: "Baran Kaya", age: 9, attendance: "expected", isExtra: false },
      { id: "oc5", name: "Selin Demir", age: 8, attendance: "expected", isExtra: false },
    ],
    payments: [
      { id: "p1", date: "2026-05-03", method: "card", amount: 500, type: "deposit", staffName: "Murat K.", note: "Depozito ödendi" },
    ],
    timeline: [
      { id: "t1", type: "created", date: "2026-05-01 10:23", title: "Rezervasyon oluşturuldu", description: "Ahmet Yılmaz tarafından telefon ile alındı.", staffName: "Murat K." },
      { id: "t2", type: "deposit", date: "2026-05-03 14:15", title: "Depozito ödendi", description: "₺500 kart ile ödendi.", staffName: "Murat K." },
      { id: "t3", type: "confirmed", date: "2026-05-03 14:20", title: "Rezervasyon onaylandı", description: "Sistem tarafından otomatik onaylandı.", staffName: "Sistem" },
      { id: "t4", type: "reminder", date: "2026-05-15 09:00", title: "Hatırlatma gönderildi", description: "3 gün öncesi SMS hatırlatması.", staffName: "Sistem" },
    ],
    operationLogs: [
      { id: "l1", date: "2026-05-01 10:23", action: "Rezervasyon oluşturuldu", staffName: "Murat K." },
      { id: "l2", date: "2026-05-03 14:15", action: "Depozito alındı: ₺500", staffName: "Murat K." },
      { id: "l3", date: "2026-05-10 11:00", action: "Çocuk listesi güncellendi (5 çocuk)", staffName: "Ayşe H." },
    ],
  },
  {
    id: "org_2",
    name: "Selin'in 7. Doğum Günü 🦄",
    childName: "Selin Öztürk",
    childAge: 7,
    parentName: "Hasan Öztürk",
    parentPhone: "0544 852 36 14",
    packageId: "pkg_vip",
    date: "2026-05-24",
    startTime: "15:00",
    endTime: "20:00",
    status: "upcoming",
    paymentStatus: "partial",
    totalAmount: 2500,
    depositAmount: 800,
    paidAmount: 1500,
    childCount: 22,
    extraChildCount: 2,
    notes: "VIP müşteri. Unicorn teması. Özel büfe istedi.",
    specialRequests: "Unicorn temalı tam dekorasyon. Özel büfe masası. Veli kokteyl alanı hazırlanmalı.",
    decorTheme: "Unicorn Teması 🦄",
    responsibleStaff: "Emre D.",
    children: [
      { id: "oc10", name: "Selin Öztürk", age: 7, attendance: "expected", isExtra: false },
      { id: "oc11", name: "Zeynep Kara", age: 7, attendance: "expected", isExtra: false },
      { id: "oc12", name: "İrem Yıldız", age: 6, attendance: "expected", isExtra: false },
      { id: "oc13", name: "Azra Çelik", age: 8, attendance: "expected", isExtra: false },
      { id: "oc14", name: "Ela Arslan", age: 7, attendance: "expected", isExtra: false },
      { id: "oc15", name: "Mia Koç", age: 7, attendance: "expected", isExtra: true },
      { id: "oc16", name: "Sara Demir", age: 6, attendance: "expected", isExtra: true },
    ],
    payments: [
      { id: "p10", date: "2026-05-02", method: "card", amount: 800, type: "deposit", staffName: "Emre D.", note: "Depozito" },
      { id: "p11", date: "2026-05-10", method: "transfer", amount: 700, type: "installment", staffName: "Emre D.", note: "1. taksit" },
    ],
    timeline: [
      { id: "t10", type: "created", date: "2026-04-28 16:00", title: "Rezervasyon oluşturuldu", staffName: "Emre D." },
      { id: "t11", type: "deposit", date: "2026-05-02 11:30", title: "Depozito ödendi (₺800)", staffName: "Emre D." },
      { id: "t12", type: "confirmed", date: "2026-05-02 11:35", title: "Rezervasyon onaylandı", staffName: "Sistem" },
      { id: "t13", type: "note", date: "2026-05-05 14:00", title: "Özel istek eklendi", description: "Unicorn teması ve büfe detayları netleştirildi.", staffName: "Ayşe H." },
    ],
    operationLogs: [
      { id: "l10", date: "2026-04-28 16:00", action: "VIP rezervasyon oluşturuldu", staffName: "Emre D." },
      { id: "l11", date: "2026-05-02 11:30", action: "Depozito alındı: ₺800", staffName: "Emre D." },
      { id: "l12", date: "2026-05-10 10:00", action: "Taksit alındı: ₺700", staffName: "Emre D." },
    ],
  },
  {
    id: "org_3",
    name: "Ali'nin 8. Doğum Günü ⚽",
    childName: "Ali Demir",
    childAge: 8,
    parentName: "Mehmet Demir",
    parentPhone: "0555 321 98 76",
    packageId: "pkg_standard",
    date: "2026-05-10",
    startTime: "11:00",
    endTime: "14:00",
    status: "ongoing",
    paymentStatus: "paid",
    totalAmount: 1200,
    depositAmount: 400,
    paidAmount: 1200,
    childCount: 13,
    extraChildCount: 1,
    notes: "Futbol teması. Tüm ödeme alındı.",
    specialRequests: "Futbol sahası dekorasyonu. Forma desenlı balon.",
    decorTheme: "Futbol Teması ⚽",
    responsibleStaff: "Selin T.",
    children: [
      { id: "oc20", name: "Ali Demir", age: 8, attendance: "arrived", isExtra: false },
      { id: "oc21", name: "Burak Yılmaz", age: 8, attendance: "arrived", isExtra: false },
      { id: "oc22", name: "Efe Kaya", age: 9, attendance: "arrived", isExtra: false },
      { id: "oc23", name: "Eren Çelik", age: 8, attendance: "arrived", isExtra: false },
      { id: "oc24", name: "Ozan Arslan", age: 7, attendance: "absent", isExtra: false },
      { id: "oc25", name: "Arda Koç", age: 8, attendance: "arrived", isExtra: true },
    ],
    payments: [
      { id: "p20", date: "2026-04-25", method: "card", amount: 400, type: "deposit", staffName: "Selin T." },
      { id: "p21", date: "2026-05-10", method: "cash", amount: 800, type: "installment", staffName: "Selin T.", note: "Gün başında kalan ödeme" },
    ],
    timeline: [
      { id: "t20", type: "created", date: "2026-04-22 09:15", title: "Rezervasyon oluşturuldu", staffName: "Selin T." },
      { id: "t21", type: "deposit", date: "2026-04-25 14:00", title: "Depozito ödendi (₺400)", staffName: "Selin T." },
      { id: "t22", type: "confirmed", date: "2026-04-25 14:05", title: "Rezervasyon onaylandı", staffName: "Sistem" },
      { id: "t23", type: "started", date: "2026-05-10 11:00", title: "Organizasyon başladı", description: "Tüm hazırlıklar tamam.", staffName: "Selin T." },
      { id: "t24", type: "children_arrived", date: "2026-05-10 11:20", title: "Çocuklar giriş yaptı", description: "13/14 çocuk katıldı. 1 devamsız.", staffName: "Selin T." },
    ],
    operationLogs: [
      { id: "l20", date: "2026-05-10 10:30", action: "Salon hazırlandı — futbol teması", staffName: "Selin T." },
      { id: "l21", date: "2026-05-10 11:00", action: "Organizasyon başlatıldı", staffName: "Selin T." },
      { id: "l22", date: "2026-05-10 11:20", action: "Çocuk girişleri tamamlandı (13/14)", staffName: "Selin T." },
    ],
  },
  {
    id: "org_4",
    name: "Elif'in 6. Doğum Günü 🌸",
    childName: "Elif Kaya",
    childAge: 6,
    parentName: "Fatma Kaya",
    parentPhone: "0543 987 65 43",
    packageId: "pkg_mini",
    date: "2026-05-05",
    startTime: "16:00",
    endTime: "18:00",
    status: "completed",
    paymentStatus: "paid",
    totalAmount: 800,
    depositAmount: 200,
    paidAmount: 800,
    childCount: 8,
    extraChildCount: 0,
    notes: "Başarılı organizasyon. Müşteri çok memnun.",
    specialRequests: "Pembe & çiçek teması.",
    decorTheme: "Çiçek Teması 🌸",
    responsibleStaff: "Ayşe H.",
    children: [
      { id: "oc30", name: "Elif Kaya", age: 6, attendance: "arrived", isExtra: false },
      { id: "oc31", name: "Buse Yıldız", age: 6, attendance: "arrived", isExtra: false },
      { id: "oc32", name: "Mira Arslan", age: 5, attendance: "arrived", isExtra: false },
      { id: "oc33", name: "Naz Demir", age: 7, attendance: "arrived", isExtra: false },
      { id: "oc34", name: "Ece Koç", age: 6, attendance: "absent", isExtra: false },
    ],
    payments: [
      { id: "p30", date: "2026-04-28", method: "cash", amount: 200, type: "deposit", staffName: "Ayşe H." },
      { id: "p31", date: "2026-05-05", method: "card", amount: 600, type: "installment", staffName: "Ayşe H." },
    ],
    timeline: [
      { id: "t30", type: "created", date: "2026-04-26 14:00", title: "Rezervasyon oluşturuldu", staffName: "Ayşe H." },
      { id: "t31", type: "deposit", date: "2026-04-28 10:30", title: "Depozito ödendi (₺200)", staffName: "Ayşe H." },
      { id: "t32", type: "confirmed", date: "2026-04-28 10:32", title: "Onaylandı", staffName: "Sistem" },
      { id: "t33", type: "started", date: "2026-05-05 16:00", title: "Organizasyon başladı", staffName: "Ayşe H." },
      { id: "t34", type: "children_arrived", date: "2026-05-05 16:15", title: "Çocuklar giriş yaptı (7/8)", staffName: "Ayşe H." },
      { id: "t35", type: "completed", date: "2026-05-05 18:05", title: "Organizasyon tamamlandı", description: "Müşteri 5 yıldız değerlendirdi.", staffName: "Ayşe H." },
    ],
    operationLogs: [
      { id: "l30", date: "2026-05-05 18:05", action: "Organizasyon başarıyla tamamlandı", staffName: "Ayşe H." },
    ],
  },
  {
    id: "org_5",
    name: "Mert'in 10. Doğum Günü 🎮",
    childName: "Mert Arslan",
    childAge: 10,
    parentName: "Kemal Arslan",
    parentPhone: "0533 456 78 90",
    packageId: "pkg_standard",
    date: "2026-06-07",
    startTime: "13:00",
    endTime: "16:00",
    status: "upcoming",
    paymentStatus: "deposit",
    totalAmount: 1200,
    depositAmount: 300,
    paidAmount: 300,
    childCount: 12,
    extraChildCount: 0,
    notes: "Oyun teması istendi.",
    specialRequests: "Gaming / Oyun teması. Joystick balon tasarımları.",
    decorTheme: "Gaming Teması 🎮",
    responsibleStaff: "Murat K.",
    children: [
      { id: "oc40", name: "Mert Arslan", age: 10, attendance: "expected", isExtra: false },
      { id: "oc41", name: "Cem Öztürk", age: 9, attendance: "expected", isExtra: false },
    ],
    payments: [
      { id: "p40", date: "2026-05-20", method: "card", amount: 300, type: "deposit", staffName: "Murat K." },
    ],
    timeline: [
      { id: "t40", type: "created", date: "2026-05-18 11:00", title: "Rezervasyon oluşturuldu", staffName: "Murat K." },
      { id: "t41", type: "deposit", date: "2026-05-20 15:00", title: "Depozito ödendi (₺300)", staffName: "Murat K." },
      { id: "t42", type: "confirmed", date: "2026-05-20 15:02", title: "Onaylandı", staffName: "Sistem" },
    ],
    operationLogs: [
      { id: "l40", date: "2026-05-18 11:00", action: "Rezervasyon oluşturuldu", staffName: "Murat K." },
    ],
  },
  {
    id: "org_6",
    name: "Defne'nin 5. Doğum Günü 🦋",
    childName: "Defne Çelik",
    childAge: 5,
    parentName: "Aylin Çelik",
    parentPhone: "0555 777 44 33",
    packageId: "pkg_premium",
    date: "2026-06-15",
    startTime: "15:00",
    endTime: "19:00",
    status: "upcoming",
    paymentStatus: "deposit",
    totalAmount: 1800,
    depositAmount: 600,
    paidAmount: 600,
    childCount: 18,
    extraChildCount: 0,
    notes: "Kelebek teması. Özel fotoğraf köşesi istendi.",
    specialRequests: "Kelebek temalı dekor. Özel fotoğraf köşesi (props dahil).",
    decorTheme: "Kelebek Teması 🦋",
    responsibleStaff: "Selin T.",
    children: [],
    payments: [
      { id: "p50", date: "2026-05-12", method: "card", amount: 600, type: "deposit", staffName: "Selin T." },
    ],
    timeline: [
      { id: "t50", type: "created", date: "2026-05-10 14:00", title: "Rezervasyon oluşturuldu", staffName: "Selin T." },
      { id: "t51", type: "deposit", date: "2026-05-12 10:00", title: "Depozito ödendi (₺600)", staffName: "Selin T." },
      { id: "t52", type: "confirmed", date: "2026-05-12 10:02", title: "Onaylandı", staffName: "Sistem" },
    ],
    operationLogs: [
      { id: "l50", date: "2026-05-10 14:00", action: "Rezervasyon oluşturuldu", staffName: "Selin T." },
    ],
  },
  {
    id: "org_7",
    name: "Hasan'ın Doğum Günü 🦸",
    childName: "Hasan Demir",
    childAge: 11,
    parentName: "Mehmet Demir",
    parentPhone: "0555 321 98 76",
    packageId: "pkg_mini",
    date: "2026-04-12",
    startTime: "14:00",
    endTime: "16:00",
    status: "cancelled",
    paymentStatus: "partial",
    totalAmount: 800,
    depositAmount: 200,
    paidAmount: 200,
    childCount: 10,
    extraChildCount: 0,
    notes: "Hasta olduğu için iptal edildi. Depozito iade bekliyor.",
    specialRequests: "",
    responsibleStaff: "Emre D.",
    children: [],
    payments: [
      { id: "p60", date: "2026-04-01", method: "cash", amount: 200, type: "deposit", staffName: "Emre D." },
    ],
    timeline: [
      { id: "t60", type: "created", date: "2026-03-28 10:00", title: "Rezervasyon oluşturuldu", staffName: "Emre D." },
      { id: "t61", type: "deposit", date: "2026-04-01 11:00", title: "Depozito ödendi (₺200)", staffName: "Emre D." },
      { id: "t62", type: "cancelled", date: "2026-04-10 09:00", title: "İptal edildi", description: "Çocuk hasta. Depozito iade süreci başlatıldı.", staffName: "Murat K." },
    ],
    operationLogs: [
      { id: "l60", date: "2026-04-10 09:00", action: "İptal işlemi yapıldı — depozito iade süreci başlatıldı", staffName: "Murat K." },
    ],
  },
]

export const MONTHLY_ORG_STATS = [
  { month: "Kas", count: 4, revenue: 5200 },
  { month: "Ara", count: 6, revenue: 8100 },
  { month: "Oca", count: 5, revenue: 7000 },
  { month: "Şub", count: 8, revenue: 11200 },
  { month: "Mar", count: 9, revenue: 13500 },
  { month: "Nis", count: 7, revenue: 9800 },
  { month: "May", count: 5, revenue: 7000 },
]

export function getOrgById(id: string): Organization | undefined {
  return ORGANIZATIONS.find((o) => o.id === id)
}

export function getPackageById(id: string) {
  return ORG_PACKAGES.find((p) => p.id === id)
}
